[workspace]
authors = ["Marina <marina.motamerlo@icm.uu.se>"]
channels = ["conda-forge", "https://conda.anaconda.org/bioconda"]
name = "pixi_assembly"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
flye = { version = ">=2.9.6,<3", channel = "bioconda" }
python = ">=3.12.12,<3.13"
snakemake = ">=9.13.6,<10"

[environments]
