name: default
channels:
- conda-forge
- https://conda.anaconda.org/bioconda
- nodefaults
dependencies:
- biopython >=1.86,<2
- spyder >=6.1.0,<7
- pandas >=2.3.3,<3
- python >=3.11.9,<3.14
- bioconda::snakemake >=9.13.6,<10

