rule all:
    input:
        "blastp/20260302_RR-TF_results.csv", 
        expand("plots/blastp_RR-TF_tree.{ext}", ext = ["png", "svg", "pdf"])

rule parse_blastp:
    output:
        "blastp/20260302_RR-TF_results.csv"
    input:
        hits = "blastp/20260302_RR-TF_HitTable.csv",
        descriptions = "blastp/20260302_RR-TF_Descriptions.csv"
    threads: 1
    log: "logs/01-parse_BLASTp.log"
#    conda: "pixi_phylo/default.yml"
    script: "code/01-merge_blastp_info.py"

rule get_faa:
    output:
        faa = "fasta/blastp_hits.faa",
        formatted = "fasta/blastp_formatted.faa"
    input:
        "blastp/20260302_RR-TF_Descriptions.csv"
    threads: 1
    log: "logs/02-get_faa.log"
#    conda: "pixi_phylo/default.yml"
    script: "code/02-get_faa.py"

rule align_seqs:
    output:
        "fasta/blastp_formatted.mafft.faa"
    input:
        "fasta/blastp_formatted.faa"
    threads: 4
    log: "logs/03-align_seqs.log"
#    conda: "pixi_phylo/default.yml"
    script: "code/03-align_seqs.py"

rule run_IQtree:
    output:
        expand("fasta/trees/blastp_formatted.mafft.faa.{ext}", ext = ["treefile", "ufboot", "splits.nex", "log", "mldist", "model.gz", "ckp.gz", "contree", "iqtree", "bionj"])
    input:
        "fasta/blastp_formatted.mafft.faa"
    threads: 24
    log: "logs/04-run_IQtree.log"
#    conda: "pixi_phylo/default.yml"
    script: "code/04-run_iqtree.py"

rule plot_tree:
    output:
        expand("plots/blastp_RR-TF_tree.{ext}", ext = ["png", "svg", "pdf"])
    input:
        tree = "fasta/trees/blastp_formatted.mafft.faa.treefile",
        hits = "blastp/20260302_RR-TF_results.csv"
    threads: 1
    log: "logs/05-plot_tree.log"
#    conda: "pixi_phylo/default.yml"
    script: "code/05-ete4_plot.py"

