[workspace]
authors = ["Marina <marina.motamerlo@icm.uu.se>"]
channels = ["conda-forge", "https://conda.anaconda.org/bioconda"]
name = "pixi_genome"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]

[dependencies]
biopython = ">=1.86,<2"
spyder = ">=6.1.0,<7"
pandas = ">=2.3.3,<3"
python = ">=3.11.9,<3.14"
snakemake = { version = ">=9.13.6,<10", channel = "bioconda" }

[feature.genome-analysis.dependencies]
samtools = { channel = "bioconda" }
bwa = { channel = "bioconda" }
prokka = { channel = "bioconda" }
blast = ">=2.16.0,<3"
circlator = ">=1.5.5,<2"
setuptools = { version = ">=80.9.0,<81", channel = "conda-forge" }
progressivemauve = { version = ">=snapshot_2015_2_13,<1a", channel = "bioconda" }
pygenomeviz = { version = ">=1.6.1,<2", channel = "conda-forge" }
multiqc = ">=1.33,<2"
fastplong = ">=0.2.1,<0.3"
seqkit = { version = ">=2.12.0,<3", channel = "bioconda" }
fastqc = ">=0.12.1,<0.13"
pbccs = { version = ">=6.4.0,<7", channel = "bioconda" }
lima = { version = ">=2.13.0,<3", channel = "bioconda" }

[feature.annotations.dependencies]
ete4 = { channel = "conda-forge" }
gffutils = { channel = "bioconda" }
pronto = { channel = "bioconda" }
requests = { channel = "conda-forge" }

[feature.annotations.pypi-dependencies]
emapper2gbk = ">=0.3.2, <0.4"

[environments]
genome-analysis = ["genome-analysis"]
annotations = ["annotations"]
